# Generated by Django 2.0.3 on 2018-03-14 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('displayOrder', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['displayOrder', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('model', models.CharField(max_length=200, unique=True, verbose_name='Model Num.')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Model Description')),
                ('size', models.CharField(blank=True, default='', max_length=200)),
                ('bikeCnt', models.IntegerField(default=0, verbose_name='Bikes')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text="Enter 0 to display 'Call for Price' message instead of actual price.", max_digits=10)),
                ('price_change_date', models.DateField(default='03/14/18')),
            ],
            options={
                'ordering': ['product__category__displayOrder', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('desc', models.TextField(blank=True, default='', verbose_name='Product Description')),
                ('image', models.CharField(blank=True, default='/images/products/sample.jpg', max_length=100, null=True, verbose_name='Full-size Image Path')),
                ('displayOrder', models.IntegerField(blank=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Category')),
            ],
            options={
                'ordering': ['displayOrder', 'name'],
            },
        ),
        migrations.AddField(
            model_name='model',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Product'),
        ),
    ]
