"""
Django settings for lindcraft project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from pathlib import Path

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


#some defaults:
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'somereallylongkeyvalue'
EMAIL_HOST = "mail.example.com"
EMAIL_HOST_USER = "ME"
EMAIL_HOST_PASSWORD = "pass"
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_ADDRESS = "you@example.com"
ADMIN_EMAIL = "me"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    "lindcraft/static",
]
ALLOWED_HOSTS = [
    # If DEBUG is False at least one allowed host is required
    '127.0.0.1',
]

# The instance directory contains the real secrets and is not commited to git
# It also allows settings to be modified in the deployment server

# create the instance directory if needed
INSTANCE_PATH = os.path.join(BASE_DIR, "instance/")
d = Path(INSTANCE_PATH)
if not d.exists():
    d.mkdir(mode=0o750)
    
#create a default instance/local_settings file if none exists
s = Path(os.path.join(d.name,"local_settings.py"))
if not s.exists():
    s.touch(mode=0o750, exist_ok=True)
    s.open(mode='w')
    i = Path(os.path.join(BASE_DIR,"default_instance_settings.txt")) 
    s.write_text(i.read_text())

#Get the local settings
from instance.local_settings import DEBUG, SECRET_KEY, EMAIL_HOST, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, EMAIL_PORT, EMAIL_USE_SSL, \
    EMAIL_ADDRESS, ADMIN_EMAIL, STATIC_URL, STATICFILES_DIRS, ALLOWED_HOSTS

# Application definition

INSTALLED_APPS = [
    'www.apps.WwwConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lindcraft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lindcraft.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'lindcraft2.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



